preload = /home/thijs/Pictures/wallpapers/gir/gir-house.png

wallpaper = HDMI-A-1,/home/thijs/Pictures/wallpapers/gir/gir-house.png
wallpaper = eDP-1,/home/thijs/Pictures/wallpapers/gir/gir-house.png
